# Generated by Django 2.0.6 on 2019-01-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.TextField(max_length=300, null=True)),
                ('download', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=150)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('txn_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.BooleanField(default=False)),
                ('stage', models.CharField(max_length=100, null=True)),
                ('profile', models.CharField(max_length=100, null=True)),
                ('fav_startup', models.TextField(null=True)),
                ('inspiration', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostRegEmpresario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acco', models.BooleanField(default=True)),
                ('size', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostRegStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('details', models.TextField(max_length=600, null=True)),
                ('website', models.URLField(max_length=100, null=True)),
                ('size', models.IntegerField(null=True)),
                ('events', models.CharField(max_length=100)),
                ('startup_seedfund', models.BooleanField(default=False)),
                ('startup_stage', models.CharField(max_length=100, null=True)),
                ('intern_number', models.IntegerField(default=0)),
                ('intern_stipend', models.CharField(max_length=100, null=True)),
                ('intern_location', models.CharField(max_length=100, null=True)),
                ('intern_profile', models.CharField(max_length=200, null=True)),
                ('intern_duration', models.CharField(max_length=100, null=True)),
                ('intern_description', models.CharField(max_length=100, null=True)),
                ('epitch_sector', models.CharField(max_length=255, null=True)),
                ('epitch_problem', models.TextField(max_length=600, null=True)),
                ('epitch_market', models.TextField(max_length=600, null=True)),
                ('epitch_revenue', models.TextField(max_length=600, null=True)),
                ('epitch_compete', models.TextField(max_length=600, null=True)),
                ('epitch_funds', models.TextField(max_length=600, null=True)),
                ('epitch_deck', models.URLField(null=True)),
                ('pexpo_type', models.CharField(max_length=20, null=True)),
                ('pexpo_details', models.TextField(max_length=600, null=True)),
                ('pexpo_demo', models.URLField(null=True)),
                ('comeet_idea', models.BooleanField(default=False)),
                ('comeet_skill_set', models.TextField(max_length=600, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.CharField(default=0, max_length=50)),
                ('departure', models.CharField(default=0, max_length=50)),
                ('pnr', models.CharField(default=0, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
