# Generated by Django 2.0.5 on 2018-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180623_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='size',
        ),
        migrations.AddField(
            model_name='travel',
            name='arrival',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='departure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='pnr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
