# Generated by Django 2.0.5 on 2018-08-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180702_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='arrival',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='departure',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='pnr',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
