# Generated by Django 2.0.5 on 2018-11-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180804_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_contingent',
        ),
        migrations.DeleteModel(
            name='join_contingent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
