# Generated by Django 2.0.6 on 2019-01-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(default='Faculty', max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=5)),
                ('stage', models.IntegerField(default=1)),
                ('link', models.CharField(default='01', max_length=100)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.College')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50)),
                ('stage', models.SmallIntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.BigIntegerField()),
                ('tshirt', models.CharField(max_length=1)),
                ('city', models.CharField(max_length=100)),
                ('college', models.CharField(default=None, max_length=150)),
                ('contingent', models.IntegerField(blank=True, default=None, null=True)),
                ('admin', models.IntegerField(default=0)),
                ('session_type', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresarioSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('startup', models.CharField(max_length=100, null=True)),
                ('track', models.CharField(max_length=100, null=True)),
                ('name1', models.CharField(max_length=100, null=True)),
                ('email1', models.EmailField(max_length=100, null=True)),
                ('mobile1', models.IntegerField(null=True)),
                ('name2', models.CharField(max_length=100, null=True)),
                ('email2', models.EmailField(max_length=100, null=True)),
                ('mobile2', models.IntegerField(null=True)),
                ('name3', models.CharField(max_length=100, null=True)),
                ('email3', models.EmailField(max_length=100, null=True)),
                ('mobile3', models.IntegerField(null=True)),
                ('name4', models.CharField(max_length=100, null=True)),
                ('email4', models.EmailField(max_length=100, null=True)),
                ('mobile4', models.IntegerField(null=True)),
                ('name5', models.CharField(max_length=100, null=True)),
                ('email5', models.EmailField(max_length=100, null=True)),
                ('mobile5', models.IntegerField(null=True)),
                ('acco', models.BooleanField(default=False)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('year_of_study', models.CharField(max_length=150)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('contact_dean', models.CharField(max_length=255)),
                ('contact_ecell', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
