# Generated by Django 2.0.5 on 2018-06-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180616_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresarioSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('startup', models.CharField(max_length=100, null=True)),
                ('track', models.CharField(max_length=100, null=True)),
                ('name1', models.CharField(max_length=100, null=True)),
                ('email1', models.EmailField(max_length=100, null=True)),
                ('mobile1', models.IntegerField(null=True)),
                ('name2', models.CharField(max_length=100, null=True)),
                ('email2', models.EmailField(max_length=100, null=True)),
                ('mobile2', models.IntegerField(null=True)),
                ('name3', models.CharField(max_length=100, null=True)),
                ('email3', models.EmailField(max_length=100, null=True)),
                ('mobile3', models.IntegerField(null=True)),
                ('name4', models.CharField(max_length=100, null=True)),
                ('email4', models.EmailField(max_length=100, null=True)),
                ('mobile4', models.IntegerField(null=True)),
                ('name5', models.CharField(max_length=100, null=True)),
                ('email5', models.EmailField(max_length=100, null=True)),
                ('mobile5', models.IntegerField(null=True)),
                ('acco', models.BooleanField(default=False)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
    ]
