# Generated by Django 2.0.5 on 2018-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_empresariosf'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='newcollege',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
