# Generated by Django 2.0.5 on 2018-07-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180702_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcollege',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
