# Generated by Django 2.0.5 on 2018-11-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180702_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contingent',
            name='contingent_id',
        ),
    ]
