# Generated by Django 2.0.6 on 2018-11-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_data_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Hall',
            new_name='alloted_hall',
        ),
    ]
