# Generated by Django 2.0.6 on 2018-11-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20181130_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='alloted_hall',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='regdesk.Hall'),
        ),
    ]
