# Generated by Django 2.0.6 on 2018-11-30 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20181130_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='alloted_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regdesk.Hall'),
        ),
    ]
