# Generated by Django 2.0.6 on 2019-01-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AltAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_num', models.IntegerField(null=True)),
                ('female_num', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('filled', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaleHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('filled', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='altallotment',
            name='female_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regdesk.FemaleHall'),
        ),
        migrations.AddField(
            model_name='altallotment',
            name='male_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regdesk.MaleHall'),
        ),
        migrations.AddField(
            model_name='altallotment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allotment',
            name='female_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regdesk.FemaleHall'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='male_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regdesk.MaleHall'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
