# Generated by Django 2.0.5 on 2018-11-29 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('filled', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='allotment',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regdesk.Hall'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
