# Generated by Django 2.0.5 on 2018-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='gender',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
